In [7]:
import numpy as np

#define calculate function where we will give our input
def calculate(list):
  if len(list)<9:
    print("List must contain nine numbers.")
    
  elif len(list)>9:
    print("Not more than nine numbers")
    
  else:
    matrix = np.array(list).reshape(3,3)
    
    print(matrix)
    
    calculations={}
    
    M0=np.mean(matrix,axis=0).tolist()     #'mean': [axis1, axis2, flattened]====>[mean of three rows, mean of three columns, mean of matrix]
    M1=np.mean(matrix,axis=1).tolist()
    M=np.mean(matrix)
    
    V0=np.var(matrix,axis=0).tolist() 
    V1=np.var(matrix,axis=1).tolist()      #same like mean
    V=np.var(matrix)
    
    S0=np.std(matrix,axis=0).tolist()      #same like mean
    S1=np.std(matrix,axis=1).tolist() 
    S=np.std(matrix)
    
    Max0=np.max(matrix,axis=0).tolist()    #same like mean
    Max1=np.max(matrix,axis=1).tolist() 
    Max=np.max(matrix)

    Min0=np.min(matrix,axis=0).tolist()    #same like mean
    Min1=np.min(matrix,axis=1).tolist() 
    Min=np.min(matrix)
    
    Sum0=np.sum(matrix,axis=0).tolist()    #same like mean
    Sum1=np.sum(matrix,axis=1).tolist() 
    Sum=np.sum(matrix)
    
    #getting calculations
    calculations['mean']=M0,M1,M 
    calculations['standard deviation']=S0,S1,S   
    calculations['Maximum']=Max0,Max1,Max   
    calculations['variance']=V0,V1,V
    calculations['Minimum']=Min0,Min1,Min    
    calculations['Sum']=Sum0,Sum1,Sum
    
    return calculations

In [8]:
calculate([14,17,51,44,23,47,65,87,54])

[[14 17 51]
 [44 23 47]
 [65 87 54]]


{'mean': ([41.0, 42.333333333333336, 50.666666666666664],
  [27.333333333333332, 38.0, 68.66666666666667],
  44.666666666666664),
 'standard deviation': ([20.92844953645635,
   31.678944988044595,
   2.8674417556808756],
  [16.77961726487096, 10.677078252031311, 13.719410418171117],
  22.395436042987768),
 'Maximum': ([65, 87, 54], [51, 47, 87], 87),
 'variance': ([438.0, 1003.5555555555557, 8.222222222222221],
  [281.5555555555556, 114.0, 188.2222222222222],
  501.55555555555554),
 'Minimum': ([14, 17, 47], [14, 23, 54], 14),
 'Sum': ([123, 127, 152], [82, 114, 206], 402)}